---

nginx_revproxy_sites:                                         # List of sites to reverse proxy
  example.com:                                                # Domain name
    client_max_body_size: "256M"
    proxy_read_timeout: "360"
    domains:                                                  # List of server_name aliases
      - www.example.com
    upstreams:                                                # List of Upstreams
      - {backend_address: backend_IP, backend_port: 80}
